In [71]:
import json
import pyiceberg
import s3fs
import boto3

import polars as pl
import pyspark as sp
import pyarrow as pa

from pyiceberg.catalog import load_catalog
#from pyiceberg.s3tables import S3TablesCatalog

In [72]:
#table_bucket_arn = 'arn:aws:s3tables:us-east-1:309820967897:bucket/edna-prod-sa-salesforce-tables/table/a23d0565-518f-4c2b-b6a1-0928cdae4464'
#aws_region = 'us-east-1'

#properties = {
#    's3tables.warehouse': table_bucket_arn,
#    's3tables.region': aws_region
#}

#catalog = S3TablesCatalog(name = 'local_discipline_incidents', **properties)

In [73]:
#### Source Files for use

#test_file = '/Users/chris.cestari/Library/Application Support/JetBrains/PyCharm2025.1/scratches/1754331709957.json'
test_file = '/Users/chris.cestari/Downloads/greenhouse_sample.json'
#test_file = '/Users/chris.cestari/Downloads/unnested_local_discipline_incidents.json'

In [74]:
df = pl.read_ndjson(test_file, infer_schema_length = None)
#display(df.head())

In [75]:
df = df.unnest('payload').unnest('payload').rename({'source': 'payload_source'})   #.unnest('payload')
df = df.unnest('application').rename({'id': 'application_id', 'source': 'application_source', 'url': 'application_url', 'custom_fields': 'application_custom_fields', 'status': 'application_status'})
df = df.unnest('credited_to').rename({'id': 'credited_to_id', 'email': 'credited_to_email', 'employee_id': 'credited_to_employee_id', 'name': 'credited_to_name'})
df = df.unnest('recruiter').rename({'id': 'recruiter_id', 'email': 'recruiter_email', 'employee_id': 'recruiter_employee_id', 'name': 'recruiter_name'})
df = df.unnest('coordinator').rename({'id': 'coordinator_id', 'email': 'coordinator_email', 'employee_id': 'coordinator_employee_id', 'name': 'coordinator_name'})
df = df.unnest('prospect_detail')
df = df.unnest('candidate').rename({'id': 'candidate_id', 'created_at': 'candidate_created_at', 'url': 'candidate_url', 'custom_fields': 'candidate_custom_fields', 'external_id': 'candidate_external_id'})
df = df.explode('jobs').unnest('jobs').rename({'id': 'job_id', 'name': 'job_name', 'notes': 'job_notes', 'created_by_id': 'job_created_by_id', 'created_at': 'job_created_at', 'closed_at': 'job_closed_at', 'url': 'job_url', 'custom_fields': 'job_custom_fields', 'status': 'job_status'})
df = df.unnest('hiring_team')
df = df.drop(['recruiter', 'coordinator'])

display(df.head(1))

shape: (1, 76)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ timestamp ┆ payload_s ┆ lambda_re ┆ environme ┆ … ┆ recruiter ┆ coordinat ┆ openings  ┆ job_cust │
│ ---       ┆ ource     ┆ quest_id  ┆ nt        ┆   ┆ s         ┆ ors       ┆ ---       ┆ om_field │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ list[stru ┆ s        │
│           ┆ str       ┆ str       ┆ str       ┆   ┆ list[stru ┆ list[stru ┆ ct[3]]    ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ ct[2]]    ┆ ct[2]]    ┆           ┆ struct[2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0]       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-09-1 ┆ greenhous ┆ 644a1d1e- ┆ non-prod  ┆ … ┆ [{4368338 ┆ [{4351476 ┆ [{4610874 ┆ {{"Agenc │
│ 0T15:05:0 ┆ e_webhook ┆ 3937-4a77 ┆           ┆   ┆ 008,"2365 ┆ 008,"2365 ┆ 008,"R001 ┆ y","shor │
│ 9.637577  ┆           ┆ -8612-178 ┆           ┆   ┆ 51"},     ┆ 63"}]     ┆ 5607-20", ┆ t_text", │
│           ┆           ┆ 704…      ┆           ┆   ┆ {43736…   ┆           ┆ {}}…      ┆ null},…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [76]:
col_list = ['phone_numbers', 'email_addresses', 'addresses', 'website_addresses', 'social_media_addresses', 'educations', 'employments', 'attachments', 'tags', 'departments', 'offices', 'hiring_managers', 'sourcers', 'recruiters', 'coordinators', 'openings']

for col in col_list:
    df = df.explode(col)

display(df.head(1))

shape: (1, 76)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ timestamp ┆ payload_s ┆ lambda_re ┆ environme ┆ … ┆ recruiter ┆ coordinat ┆ openings  ┆ job_cust │
│ ---       ┆ ource     ┆ quest_id  ┆ nt        ┆   ┆ s         ┆ ors       ┆ ---       ┆ om_field │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ struct[3] ┆ s        │
│           ┆ str       ┆ str       ┆ str       ┆   ┆ struct[2] ┆ struct[2] ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ struct[2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0]       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-09-1 ┆ greenhous ┆ 644a1d1e- ┆ non-prod  ┆ … ┆ {43683380 ┆ {43514760 ┆ {46108740 ┆ {{"Agenc │
│ 0T15:05:0 ┆ e_webhook ┆ 3937-4a77 ┆           ┆   ┆ 08,"23655 ┆ 08,"23656 ┆ 08,"R0015 ┆ y","shor │
│ 9.637577  ┆           ┆ -8612-178 ┆           ┆   ┆ 1"}       ┆ 3"}       ┆ 607-20",{ ┆ t_text", │
│           ┆           ┆ 704…      ┆           ┆   ┆           ┆           ┆ }}        ┆ null},…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [77]:
df = df.unnest('attachments').rename({'filename': 'attachment_filename', 'url': 'attachment_url', 'type': 'attachment_type'})
df = df.unnest('hiring_managers').rename({'user_id': 'hiring_mgr_user_id', 'employee_id': 'hiring_mgr_employee_id'})
df = df.unnest('recruiters').rename({'user_id': 'recruiter_user_id', 'employee_id': 'recruiters_employee_id'})
df = df.unnest('openings').rename({'id': 'opening_id', 'opening_id': 'opening_opening_id', 'custom_fields': 'opening_custom_fields'})
df = df.unnest('departments').rename({'id': 'department_id', 'name': 'department_name', 'external_id': 'department_external_id'})
df = df.unnest('offices').rename({'id': 'office_id', 'name': 'office_name', 'location': 'location_name', 'external_id': 'office_external_id'})
df = df.unnest('application_source').rename({'id': 'application_source_id', 'name': 'application_source_name'})
df = df.unnest('coordinators').rename({'user_id': 'hr_team_coordinator_user_id', 'employee_id': 'hr_team_coordinator_employee_id'})
display(df.head(1))

shape: (1, 89)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ timestamp ┆ payload_s ┆ lambda_re ┆ environme ┆ … ┆ opening_i ┆ opening_o ┆ opening_c ┆ job_cust │
│ ---       ┆ ource     ┆ quest_id  ┆ nt        ┆   ┆ d         ┆ pening_id ┆ ustom_fie ┆ om_field │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ lds       ┆ s        │
│           ┆ str       ┆ str       ┆ str       ┆   ┆ i64       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ struct[0] ┆ struct[2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0]       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-09-1 ┆ greenhous ┆ 644a1d1e- ┆ non-prod  ┆ … ┆ 461087400 ┆ R0015607- ┆ {}        ┆ {{"Agenc │
│ 0T15:05:0 ┆ e_webhook ┆ 3937-4a77 ┆           ┆   ┆ 8         ┆ 20        ┆           ┆ y","shor │
│ 9.637577  ┆           ┆ -8612-178 ┆           ┆   ┆           ┆           ┆           ┆ t_text", │
│           ┆           ┆ 704…      ┆           ┆   ┆           ┆           ┆           ┆ null},…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

application_source credited_to	applicant_recruiter  applicant_coordinator  prospect_detail  are_you_a_parent_to_an_sa_scholar_  are_you_authorized_to_work_in_the_united_states_
borough_preference_  confirmed_desired_salary  do_you_have_a_family_or_close_personal_relationship_with_anyone_in_the_success_academy_charter_schools__community__includes_employees__students__and_students__families__
earliest_start_month  have_you_previously_worked_for_success_academy_charter_schools_  if_referral__please_provide_the_individual_s_name_
if_yes__please_provide_the_individual_s_name_  will_you_now_or_in_the_future_require_sponsorship_for_employment_visa_status_in_order_to_work_for_success_academy_charter_schools_	
candidate  departments	  offices	hiring_team	openings	custom_fields

s3path = 
# Constants
REGION = 'us-east-1'
CATALOG = 's3tablescatalog'
DATABASE = 'edna-greenhouse-applications'
TABLE_BUCKET = 'greenhouuse_application_data'
TABLE_NAME = 'customers'

In [78]:
#df.columns

In [79]:
# Deconstruct to match raw_greenhouse tables
df_candidates = df.select(['candidate_id', 'first_name', 'last_name', 'preferred_name', 'title', 'company','candidate_created_at', 'last_activity_at', 'is_private', 'organization_id']).rename({'candidate_id': 'id', 'candidate_created_at': 'created_at', 'last_activity_at': 'updated_at', 'is_private': 'private'}).unique()
df_applications = df.select(['application_id', 'candidate_id', 'applied_at', 'application_status', 'prospect', 'application_source_id', 'job_post_id', 'prospect_pool', 'prospect_stage', 'prospect_owner', 'last_activity_at', 'organization_id', 'recruiter_id', 'coordinator_id', 'recruiter_name', 'coordinator_name']).rename({'application_status': 'status', 'application_source_id': 'source_id', 'last_activity_at': 'updated_at', 'recruiter_name': 'recruiter', 'coordinator_name': 'coordinator'}).unique()
display(df_applications)

shape: (1, 16)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ applicatio ┆ candidate_ ┆ applied_a ┆ status ┆ … ┆ recruiter ┆ coordinat ┆ recruiter ┆ coordinat │
│ n_id       ┆ id         ┆ t         ┆ ---    ┆   ┆ _id       ┆ or_id     ┆ ---       ┆ or        │
│ ---        ┆ ---        ┆ ---       ┆ str    ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│ i64        ┆ i64        ┆ str       ┆        ┆   ┆ i64       ┆ i64       ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 4371941300 ┆ 3796125400 ┆ 2025-07-1 ┆ hired  ┆ … ┆ 436833800 ┆ 435147600 ┆ Erin      ┆ Joseph    │
│ 8          ┆ 8          ┆ 4T05:35:0 ┆        ┆   ┆ 8         ┆ 8         ┆ Kneucker  ┆ Cantu     │
│            ┆            ┆ 3Z        ┆        ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [80]:
#sts_client = boto3.client('sts')
s3tables_client = boto3.client(
        's3tables',
        region_name = 'us-east-1',
        aws_access_key_id = 'ASIAS7UJFOVMTU2FQ4A6',
        aws_secret_access_key = 'yVVkm7Q80BnU71aYMR6B3qaFsahk5iS1AeRcT1YN'    ,
        aws_session_token = "IQoJb3JpZ2luX2VjEH0aCXVzLWVhc3QtMSJHMEUCICDDkT5gg8ZrS1VkaAu4aiJssYZVHAulrehJFHvlPuIeAiEA+eO35a4tdGfr34x0MXzG5FMdXocsEPKqCpFP5Xdrq50qogMIFhABGgwyMDUzNzIzNTU5MjkiDBi8/WF8foUFxUhtlyr/ArZOiLvayQWEvZVfrXwWn/cau1T6l0zS3QSYij7F51kCsDzX5iMa4LowyUeLChIBGIjd5JHQgx2DWbw+fGiB/ubOEqJYlK4p3/x07JbDdvM/GzgYZ9hQV+FopELnAjNkkrWkfPmPbrMaf4y+5MeC8JcYcvw2PuEfuc3TaEljx7/YzwsydOhtZU9Llp/RxK/EDuqORhFFny5OiCCeOKawp7xJvSO7ihOJp0fZnbqppAI+PGTIVXoyzntodMMZB0oYGpWHLa8kqOVRGkwoN8xCPheiJk8VzcoiVNcuWiijUjG18Jf7Czgv5a0/g5lD8KSF0U56vvEP1gLfS/uCG1GsGZQXpXyhKbSGjka7a1XPcU62KWvBcIoRM+G/tceZ9GBjLETTbiCsJjeclcWMLVjZ4jlSyoJeIno4Q3rUIeSZsOGb63lo6qx6e/k/WZHSjLwkJC2BW3/uqJzoLw/ssHHrj943u+OKWbeKkDXKvmPzShD3dQjIdcAY5XwbdTS1yrVkMK3F9MYGOqYBx/BvQk+6eoSH5zPG7vkFjETtuG+TsSEc6IQel1DPdywvsNQsEjbklhK/lkDiqzT9UFWCFbcYIh4ReZrGTkkIn4verZ2dQuxjtEpau0V0YfX1Y1BYZIpFIXwBoSbePWn0YwEeU4GD18RO4TJjc0x1wAi2ogFHG4Is95L71WAlAZdA39EkaEoSk1ckl3rm44e1O8ol62YXfBS/Y8i/c/OlzA6FJQBeIQ=="
)

In [91]:
glue_client = boto3.client(
    'glue',
    region_name = 'us-east-1',
    aws_access_key_id = 'ASIAS7UJFOVMTU2FQ4A6',
    aws_secret_access_key = 'yVVkm7Q80BnU71aYMR6B3qaFsahk5iS1AeRcT1YN'    ,
    aws_session_token = "IQoJb3JpZ2luX2VjEH0aCXVzLWVhc3QtMSJHMEUCICDDkT5gg8ZrS1VkaAu4aiJssYZVHAulrehJFHvlPuIeAiEA+eO35a4tdGfr34x0MXzG5FMdXocsEPKqCpFP5Xdrq50qogMIFhABGgwyMDUzNzIzNTU5MjkiDBi8/WF8foUFxUhtlyr/ArZOiLvayQWEvZVfrXwWn/cau1T6l0zS3QSYij7F51kCsDzX5iMa4LowyUeLChIBGIjd5JHQgx2DWbw+fGiB/ubOEqJYlK4p3/x07JbDdvM/GzgYZ9hQV+FopELnAjNkkrWkfPmPbrMaf4y+5MeC8JcYcvw2PuEfuc3TaEljx7/YzwsydOhtZU9Llp/RxK/EDuqORhFFny5OiCCeOKawp7xJvSO7ihOJp0fZnbqppAI+PGTIVXoyzntodMMZB0oYGpWHLa8kqOVRGkwoN8xCPheiJk8VzcoiVNcuWiijUjG18Jf7Czgv5a0/g5lD8KSF0U56vvEP1gLfS/uCG1GsGZQXpXyhKbSGjka7a1XPcU62KWvBcIoRM+G/tceZ9GBjLETTbiCsJjeclcWMLVjZ4jlSyoJeIno4Q3rUIeSZsOGb63lo6qx6e/k/WZHSjLwkJC2BW3/uqJzoLw/ssHHrj943u+OKWbeKkDXKvmPzShD3dQjIdcAY5XwbdTS1yrVkMK3F9MYGOqYBx/BvQk+6eoSH5zPG7vkFjETtuG+TsSEc6IQel1DPdywvsNQsEjbklhK/lkDiqzT9UFWCFbcYIh4ReZrGTkkIn4verZ2dQuxjtEpau0V0YfX1Y1BYZIpFIXwBoSbePWn0YwEeU4GD18RO4TJjc0x1wAi2ogFHG4Is95L71WAlAZdA39EkaEoSk1ckl3rm44e1O8ol62YXfBS/Y8i/c/OlzA6FJQBeIQ=="
)

In [92]:
catalog = load_catalog(
    name = 's3tablescatalog',
    **{
        'type': 'glue',
        'client.region': 'us-east-1',
        'uri': 'https://us-east-1.console.aws.amazon.com/s3/table-buckets/edna-greenhouse-applications/?region=us-east-1'
    }
    
)
print(catalog)

s3tablescatalog (<class 'pyiceberg.catalog.glue.GlueCatalog'>)

In [93]:
df_candidates_arrow = df_candidates.to_arrow()
df_applications_arrow = df_applications.to_arrow()

In [94]:
# Fully qualified table identifier
candidates_table_identifier = ('edna-greenhouse-applications', 'applications')
applications_table_identifier = ('edna-greenhouse-applications', 'candidates')

try:
    # 1. Load the existing Iceberg table
    table = catalog.load_table('edna-greenhouse-applications.candidates')

    # 2. Use the transaction to append the new data
    # The 'append' method writes the Arrow Table data files (usually Parquet) 
    # to the S3 data location defined by the table's metadata and commits a new snapshot.
    with table.transaction() as tx:
        tx.append(df_candidates_arrow)

    print(f"Successfully appended {len(df)} rows to Iceberg table '{'Idf_candidates_arrow'}'.")

except Exception as e:
    print(f"Error interacting with Iceberg table: {e}")

Error interacting with Iceberg table: Unable to locate credentials

In [69]:
#catalog = load_catalog(
#    "s3tablescatalog",
#    **{
#        "uri": "https://us-east-1.console.aws.amazon.com/s3/table-buckets/edna-greenhouse-applications/?region=us-east-1",
#        "s3.endpoint": "http://127.0.0.1:9000",
#        "py-io-impl": "pyiceberg.io.pyarrow.PyArrowFileIO",
#        "s3.access-key-id": "admin",
#        "s3.secret-access-key": "password",
#    }
#)

In [53]:
response = s3tables_client.list_tables(
    tableBucketARN = 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications',
    namespace = 'greenhouse_application_data',
    maxTables = 100
)
print(response)

{'ResponseMetadata': {'RequestId': 'a887838c-b161-4443-b488-986fada65e66', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'a887838c-b161-4443-b488-986fada65e66', 'content-type': 'application/json', 'content-length': '24526', 'date': 'Wed, 01 Oct 2025 12:52:22 GMT'}, 'RetryAttempts': 0}, 'tables': [{'namespace': ['greenhouse_application_data'], 'name': 'agency_question_custom_fields', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/9e18cd7d-d941-4165-a531-e4c6e06b152c', 'createdAt': datetime.datetime(2025, 9, 17, 15, 48, 48, 457649, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 17, 15, 48, 48, 782726, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'application_custom_fields', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/86c4f3e9-1c89-4020-8044-6df6c525a33a', 'createdAt': datetime.datetime(2025, 9, 15, 19, 23, 1, 130420, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 15, 19, 23, 1, 595437, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'application_jobs', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/f920f073-72a2-4cd1-a00e-f90b2946a751', 'createdAt': datetime.datetime(2025, 9, 15, 19, 35, 37, 341325, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 15, 19, 35, 37, 652637, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'application_question_answers', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/cd15aba5-e947-4d28-8c2c-9e7f488cc63e', 'createdAt': datetime.datetime(2025, 9, 15, 19, 24, 34, 916504, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 15, 19, 24, 35, 339679, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'application_stages', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/66dddc1e-68d9-4306-b6dc-8c9a5cffe0a8', 'createdAt': datetime.datetime(2025, 9, 15, 19, 26, 40, 883774, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 15, 19, 26, 41, 239256, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'applications', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/a92376ab-88ab-4dfb-90ae-10a0e69356cf', 'createdAt': datetime.datetime(2025, 9, 15, 19, 34, 21, 297109, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 15, 19, 34, 21, 657721, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'approvals', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/aa8dac10-2027-44b6-8be4-ebf483f88063', 'createdAt': datetime.datetime(2025, 9, 15, 19, 45, 52, 949177, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 15, 19, 45, 53, 404287, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'attributes', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/18ba35e1-ce9a-4dfe-b9de-07a7aad885dc', 'createdAt': datetime.datetime(2025, 9, 15, 20, 56, 41, 262085, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 15, 20, 56, 41, 576463, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'audit_log', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/d6accf49-e186-4b97-948f-326e5fb9e40c', 'createdAt': datetime.datetime(2025, 9, 15, 20, 58, 48, 437741, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 15, 20, 58, 48, 788470, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'candidate_custom_fields', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/c0f6e597-11bd-487d-8328-3e4dd7760135', 'createdAt': datetime.datetime(2025, 9, 15, 21, 1, 0, 196525, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 15, 21, 1, 0, 576052, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'candidate_email_addresses', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/5be4450f-019c-4e42-9f2c-e8e4e2023336', 'createdAt': datetime.datetime(2025, 9, 15, 21, 1, 51, 888140, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 15, 21, 1, 52, 229968, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'candidate_mailing_addresses', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/5dec7921-e6be-4909-a1db-aca7109a7b7d', 'createdAt': datetime.datetime(2025, 9, 15, 21, 2, 50, 376938, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 15, 21, 2, 50, 747595, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'candidate_phone_numbers', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/f55d95b3-e17e-49ee-b855-ef38fffb9797', 'createdAt': datetime.datetime(2025, 9, 15, 21, 3, 52, 849488, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 15, 21, 3, 53, 197129, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'candidates', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/e2cebbb3-ae14-4b63-9cc2-39f378a383c9', 'createdAt': datetime.datetime(2025, 9, 15, 21, 5, 31, 223048, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 15, 21, 5, 31, 598223, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'candidates_tags', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/fc4462e1-5737-4107-a360-2cdd0ca4eb7c', 'createdAt': datetime.datetime(2025, 9, 16, 12, 49, 43, 629578, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 12, 49, 43, 935026, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'delivered_candidate_surveys', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/6b818e32-2fef-4cea-b5d7-528d2a441854', 'createdAt': datetime.datetime(2025, 9, 16, 12, 51, 2, 899405, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 12, 51, 3, 263012, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'demographic_answer_option_translations', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/1bbae543-dbad-4162-ae67-a3015a955c7c', 'createdAt': datetime.datetime(2025, 9, 16, 12, 52, 5, 56796, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 12, 52, 5, 469196, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'demographic_answer_options', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/aafe4b56-e120-418b-8571-a534d0a35845', 'createdAt': datetime.datetime(2025, 9, 16, 12, 53, 13, 283689, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 12, 53, 13, 622453, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'demographic_answers', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/59668903-a4b1-418c-a516-4fc8594c4011', 'createdAt': datetime.datetime(2025, 9, 16, 12, 54, 28, 286850, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 12, 54, 28, 647122, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'demographic_free_form_answers', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/f584157c-714b-42e1-8908-951fc26b47bd', 'createdAt': datetime.datetime(2025, 9, 16, 12, 56, 7, 721878, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 12, 56, 8, 68296, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'demographic_question_sets', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/95774842-d4e1-4476-bbb6-f19bc374cf38', 'createdAt': datetime.datetime(2025, 9, 16, 12, 57, 55, 412266, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 12, 57, 55, 723457, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'demographic_question_translations', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/ec4cc1b6-bbe7-46ab-9fe2-97aba8fca33b', 'createdAt': datetime.datetime(2025, 9, 16, 12, 58, 50, 178231, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 12, 58, 50, 512725, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'demographic_questions', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/e4051b73-cbd3-4b58-ab5f-62bbfed0765f', 'createdAt': datetime.datetime(2025, 9, 16, 13, 0, 5, 650481, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 0, 6, 29631, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'departments', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/1e01995f-692f-4d26-bb0b-5e6cb038d13d', 'createdAt': datetime.datetime(2025, 9, 16, 13, 1, 8, 560705, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 1, 8, 905862, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'educations', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/d109a9e1-7d3a-4889-b764-98ab7506dfae', 'createdAt': datetime.datetime(2025, 9, 16, 13, 3, 36, 70329, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 3, 36, 366934, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'eeoc_responses', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/1972a4a7-a1bd-4ede-a9e3-6ff9e81ba4bb', 'createdAt': datetime.datetime(2025, 9, 16, 13, 4, 49, 974031, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 4, 50, 314921, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'employments', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/a453f737-cc99-44ff-a728-7ea7888dec2a', 'createdAt': datetime.datetime(2025, 9, 16, 13, 5, 59, 437011, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 5, 59, 778100, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'events', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/d6da422c-4f66-4404-83c8-a05784cbaefc', 'createdAt': datetime.datetime(2025, 9, 16, 13, 7, 17, 699618, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 7, 18, 52831, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'gdpr_consent_decisions', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/33f68290-5b1b-45fe-a474-b1dad765ef9d', 'createdAt': datetime.datetime(2025, 9, 16, 13, 8, 18, 674347, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 8, 18, 992621, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'gdpr_consent_requests', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/50c67a42-4d1b-423f-8b41-4d758203e38c', 'createdAt': datetime.datetime(2025, 9, 16, 13, 9, 18, 94442, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 9, 18, 514613, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'gdpr_office_rules', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/c7d1a841-14a5-4064-bbd0-da141beb93fd', 'createdAt': datetime.datetime(2025, 9, 16, 13, 10, 4, 363908, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 10, 4, 716222, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'greenhouse_usages', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/3960738a-fb9f-4495-9bb9-c00631b86514', 'createdAt': datetime.datetime(2025, 9, 16, 13, 15, 39, 751798, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 15, 40, 124039, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'hiring_team', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/e55a5d2e-3b9d-4564-b394-58f14ea46d55', 'createdAt': datetime.datetime(2025, 9, 16, 13, 16, 40, 976182, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 16, 41, 283270, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'interviewer_tags', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/105d3cc5-a062-4241-b670-8b118cdc9970', 'createdAt': datetime.datetime(2025, 9, 16, 13, 17, 45, 669922, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 17, 46, 18021, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'interviewers', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/ddfd2839-1e38-42d1-9622-ae58e4fc90d4', 'createdAt': datetime.datetime(2025, 9, 16, 13, 18, 45, 936108, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 18, 46, 273858, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'interviews', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/9a83377f-8ac1-4ced-8a12-55c39db8a6fb', 'createdAt': datetime.datetime(2025, 9, 16, 13, 19, 53, 497633, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 19, 53, 852663, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'job_custom_fields', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/86be6bb1-1f96-414b-bb57-361331eda695', 'createdAt': datetime.datetime(2025, 9, 16, 13, 22, 46, 989044, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 13, 22, 47, 354736, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'job_post_locations', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/c99a6def-f6ab-4c9f-a00a-28e1e21a143a', 'createdAt': datetime.datetime(2025, 9, 16, 19, 17, 56, 120882, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 19, 17, 56, 570765, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'job_post_questions', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/4d7258d5-542a-4dbe-9346-90544a9c9d5b', 'createdAt': datetime.datetime(2025, 9, 16, 19, 19, 4, 420671, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 19, 19, 4, 776158, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'job_posts', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/9e67c10d-7f9c-4e02-ba42-ef0029fc0fbc', 'createdAt': datetime.datetime(2025, 9, 16, 19, 21, 30, 757931, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 19, 21, 31, 251501, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'job_posts_updated', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/e8b357a3-102e-4282-bba6-6c5864f6a214', 'createdAt': datetime.datetime(2025, 9, 16, 19, 23, 19, 495658, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 19, 23, 19, 829786, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'job_snapshots', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/e5f552b2-3d41-4a3b-b355-35fa5045be9c', 'createdAt': datetime.datetime(2025, 9, 16, 19, 26, 2, 645059, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 19, 26, 3, 30895, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'jobs', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/e93d88b5-9c69-41b0-aec1-93bd4c12326a', 'createdAt': datetime.datetime(2025, 9, 16, 19, 29, 7, 263404, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 19, 29, 7, 607537, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'jobs_attributes', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/382d4370-9b42-4a74-965f-ac3ac1300955', 'createdAt': datetime.datetime(2025, 9, 16, 20, 19, 35, 653293, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 20, 19, 35, 980354, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'jobs_departments', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/46000120-5c7f-494e-8b87-7306cd5d9af8', 'createdAt': datetime.datetime(2025, 9, 16, 20, 20, 24, 537552, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 20, 20, 24, 897210, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'jobs_interviews', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/0c0691eb-e2d8-40a5-9f6d-14a67d853fda', 'createdAt': datetime.datetime(2025, 9, 16, 20, 22, 26, 438932, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 20, 22, 26, 856100, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'jobs_offices', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/a372e74e-0e9e-4ecf-9de4-f32ce328cc85', 'createdAt': datetime.datetime(2025, 9, 16, 20, 25, 33, 6147, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 20, 25, 33, 468178, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'jobs_stages', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/c0558555-114a-4315-a160-8c253ae51983', 'createdAt': datetime.datetime(2025, 9, 16, 20, 29, 44, 265041, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 20, 29, 44, 647186, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'offer_custom_fields', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/5030dad4-8a8d-4920-b669-366842c532b1', 'createdAt': datetime.datetime(2025, 9, 16, 20, 34, 15, 677913, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 20, 34, 16, 50360, tzinfo=tzutc())}, {'namespace': ['greenhouse_application_data'], 'name': 'offers', 'type': 'customer', 'tableARN': 'arn:aws:s3tables:us-east-1:205372355929:bucket/edna-greenhouse-applications/table/7a1e55c1-1cc8-4f09-924a-5ff42d7596e5', 'createdAt': datetime.datetime(2025, 9, 16, 20, 35, 58, 807586, tzinfo=tzutc()), 'modifiedAt': datetime.datetime(2025, 9, 16, 20, 35, 59, 140278, tzinfo=tzutc())}, {'namespace': ['greenhouse_applic

In [ ]:
print(account_id)

In [ ]:
account_id = sts_client.get_caller_identity().get('Account')

In [ ]:
http://localhost:8889/opt/anaconda3/lib/python3.13/site-packages/botocore/context.py#line=122

In [ ]:
edna_gh_catalog = load_catalog(
    's3tablescatalog',
    **{
        'type': 'rest',
        'warehouse': f'{account_id}:s3tablescatalog/greenhouse_application_data',
        'uri': 'https://glue.us-east1.amazonaws.com/iceberg',
        'rest.sigv4-enabled': 'true',
        'rest.signing-name': 'glue',
        'rest.signing-region': 'us-east1'
    }
)

In [ ]:
def dataframe_flattener(dataframe: pl.DataFrame): #-> pl.DataFrame:
    struct_cols = [col for col, dtype in dataframe.schema.items() if dtype == pl.Struct]
    list_cols = [col for col, dtype in dataframe.schema.items() if dtype == pl.List]

    print(struct_cols)
    print(list_cols)
    #while struct_cols:
    
    for col in struct_cols:
        dataframe = dataframe.with_columns(pl.col(col).struct.rename_fields([f'{col}_{field}' for field in df[col].struct.fields]))
        dataframe.unnest(col)   #.name.prefix(f'{col}_')

    for col in list_cols:
        dataframe = dataframe.with_columns(pl.col(col).explode())

    return(dataframe)

In [ ]:
structs = dataframe_flattener(df)
print(structs)

In [ ]:
def dataframe_flattener2(dataframe: pl.DataFrame):
    struct_cols = [col for col, dtype in dataframe.schema.items() if dtype == pl.Struct]
    list_cols = [col for col, dtype in dataframe.schema.items() if dtype == pl.List]
    print(struct_cols, list_cols)
    for col in struct_cols:
        dataframe = dataframe.with_columns(pl.col(col).name.prefix_fields(f'{col}_'))
        dataframe = dataframe[col].struct.unnest()

    for col in list_cols:
        dataframe = dataframe.with_columns(pl.col(col).explode())

    return dataframe

In [ ]:
df = dataframe_flattener2(df)
display(df)

In [ ]:
df = df.with_columns(pl.col('source').name.prefix_fields('source_'))
df = df.with_columns(pl.col('recruiter').name.prefix_fields('recruiter_'))
df = df.with_columns(pl.col('coordinator').name.prefix_fields('coordinator'))
df = df.with_columns(pl.col('current_stage').name.prefix_fields('prospect_detail'))

df.unnest(['source', 'recruiter', 'coordinator', 'current_stage'])
print(df)

In [ ]:
structs_flatter = dataframe_flattener(structs)
print(structs_flatter)

In [ ]:
print(df.schema.items())

In [ ]:
df = df.unnest(['current_stage', 'prospect_detail', 'custom_fields', 'candidate'])
display(df)